### PR TITLE
Fix settings config loading

### PR DESCRIPTION
**Pull request by mullermp**
Fix usage of `config.action_mailer.<mailer>_settings` by adding delivery method after initializing railties.

### CODE REVIEW

**Comment by mullermp** [comment]
@admtnnr

**Comment by admtnnr** [comment]
LGTM. Sorry about that!

**Comment by mullermp** [comment]
No worries.. doesn't hurt to double check. I also just added some railtie tests.

**Comment by admtnnr** [comment]
Yep, looks good. Was just about to ask if we could add something to the dummy app to catch this case when I saw your second commit come through. 👍

**Review by jterapin — APPROVED** [review]
🚢✨

**Pull request merged**
